package agentkit

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"

	"github.com/eadwinCode/agent-kit/go/internal/jsonutil"
)

// fixtures.json is generated by packages/agent-kit/scripts/emit-fixtures.mjs
// from real JSON.stringify output at the TS construction sites. Regenerate:
//
//	cd packages/agent-kit && node scripts/emit-fixtures.mjs > ../../go/internal/testdata/fixtures.json
type fixtureFile struct {
	Cases []struct {
		Name         string `json:"name"`
		JSON         string `json:"json"`
		SemanticOnly bool   `json:"semanticOnly"`
	} `json:"cases"`
	UserMessage struct {
		JSON string `json:"json"`
	} `json:"userMessage"`
	AgentResult struct {
		JSON       string `json:"json"`
		Checksum   string `json:"checksum"`
		ExportJSON string `json:"exportJson"`
	} `json:"agentResult"`
}

func loadFixtures(t *testing.T) fixtureFile {
	t.Helper()
	b, err := os.ReadFile("internal/testdata/fixtures.json")
	if err != nil {
		t.Fatalf("fixtures missing (regenerate with emit-fixtures.mjs): %v", err)
	}
	var f fixtureFile
	if err := json.Unmarshal(b, &f); err != nil {
		t.Fatal(err)
	}
	if len(f.Cases) == 0 {
		t.Fatal("no fixture cases")
	}
	return f
}

// TestMessageWireParity: every TS-emitted message must round-trip through
// the Go Message type back to the exact same bytes. semanticOnly cases
// (U+2028/U+2029: encoding/json always escapes them, JSON.stringify never
// does) are compared as parsed values instead.
func TestMessageWireParity(t *testing.T) {
	f := loadFixtures(t)
	for _, c := range f.Cases {
		t.Run(c.Name, func(t *testing.T) {
			var m Message
			if err := json.Unmarshal([]byte(c.JSON), &m); err != nil {
				t.Fatalf("unmarshal TS fixture: %v", err)
			}
			out, err := jsonutil.Marshal(m)
			if err != nil {
				t.Fatalf("marshal back: %v", err)
			}
			if c.SemanticOnly {
				assertSemanticEqual(t, []byte(c.JSON), out)
				return
			}
			if string(out) != c.JSON {
				t.Errorf("byte mismatch:\n ts: %s\n go: %s", c.JSON, out)
			}
		})
	}
}

func TestUserMessageWireParity(t *testing.T) {
	f := loadFixtures(t)
	var u UserMessage
	if err := json.Unmarshal([]byte(f.UserMessage.JSON), &u); err != nil {
		t.Fatal(err)
	}
	out, err := jsonutil.Marshal(u)
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != f.UserMessage.JSON {
		t.Errorf("byte mismatch:\n ts: %s\n go: %s", f.UserMessage.JSON, out)
	}
}

// TestAgentResultWireParity: the memoized-step shape (full struct), the
// export() persistence shape, and — the load-bearing one — the checksum must
// all match the TS output for the same logical result.
func TestAgentResultWireParity(t *testing.T) {
	f := loadFixtures(t)

	var r AgentResult
	if err := json.Unmarshal([]byte(f.AgentResult.JSON), &r); err != nil {
		t.Fatal(err)
	}

	sum, err := r.Checksum()
	if err != nil {
		t.Fatal(err)
	}
	if sum != f.AgentResult.Checksum {
		t.Errorf("cross-runtime checksum mismatch:\n ts: %s\n go: %s", f.AgentResult.Checksum, sum)
	}

	out, err := jsonutil.Marshal(&r)
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != f.AgentResult.JSON {
		t.Errorf("full-struct byte mismatch:\n ts: %s\n go: %s", f.AgentResult.JSON, out)
	}

	export, err := r.Export()
	if err != nil {
		t.Fatal(err)
	}
	exportOut, err := jsonutil.Marshal(export)
	if err != nil {
		t.Fatal(err)
	}
	if string(exportOut) != f.AgentResult.ExportJSON {
		t.Errorf("export byte mismatch:\n ts: %s\n go: %s", f.AgentResult.ExportJSON, exportOut)
	}
}

// TestChecksumMemoInvalidatedByID mirrors the TS memo semantics: reading the
// checksum before the durable id is assigned must not pin a stale hash.
func TestChecksumMemoInvalidatedByID(t *testing.T) {
	r := NewAgentResult("a", []Message{{
		Type: MessageText, Role: RoleAssistant, Content: TextContent("hi"), StopReason: StopStop,
	}}, nil, jsonutil.Now())

	before, err := r.Checksum()
	if err != nil {
		t.Fatal(err)
	}
	r.ID = "msg_late_id"
	after, err := r.Checksum()
	if err != nil {
		t.Fatal(err)
	}
	if before == after {
		t.Error("checksum memo not invalidated when ID was assigned after first read")
	}
	again, _ := r.Checksum()
	if again != after {
		t.Error("checksum not stable after ID settled")
	}
}

func assertSemanticEqual(t *testing.T, want, got []byte) {
	t.Helper()
	var w, g any
	if err := json.Unmarshal(want, &w); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(got, &g); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(w, g) {
		t.Errorf("semantic mismatch:\nwant %s\n got %s", want, got)
	}
}
